pkg/cache/cache.go
pkg/cache/resource-store.go
pkg/idling/controller.go
pkg/idling/idle.go

scale rcs w/out dcs and only consider scalable pods for idling (pods w/ services)

---

LICENSE

Add Apache v2 LICENSE.

---

pkg/idling/idle.go

@damemi found an error in the idled-at annotation cleanup during previous-scale annotation. I missed this with the last PR.  This PR fixes the AnnotateService function so it actually deletes stale idled-at annotations, also when idled-at target already exists, I was skipping the AnnotateeController call, so controller idled-at annotations were also not getting cleared during previous-scale annotation.  Yikes, please approve and merge!

fixup in annotate-service

---

pkg/cache/resource-store_test.go
pkg/forcesleep/forcesleep.go
pkg/forcesleep/forcesleep_test.go

@damemi 
1) Added the extra check back for 'Check if quota doesn't exist and should' in forcesleep.go
2) Fixed up unit tests in pkg/cache
3) Fixed integration tests in pkg/forcesleep

fix tests, add tests

---

pkg/idling/controller.go

@dgoodwin I'm adding a RateLimitingQueue to handle the auto-idling, should've had this from the beginning.. i'm learning :)  
I've tested in a devenv, everything is working as expected.

Hawkular query pause

---

pkg/cache/cache.go
pkg/forcesleep/forcesleep.go
pkg/idling/controller.go
pkg/idling/idle.go

@damemi @dgoodwin 
changing 'errors.New(fmt.Sprintf(".."))' to 'fmt.Errorf("...")' throughout.   That's it!

error msg fixup

---

pkg/idling/controller.go

@dgoodwin @damemi please review.  I've tested in a devenv, killing hawkular-metrics pod creates the requeueing, I can see 3 hawkular queries per project per syncProject, as expected.

add MaxRetries to workqueue

---

README.md

This patch fix the markdown in the README title.
Signed-off-by: Marcela Bonell <marcelabonell@gmail.com>

Fix markdown title

---

README.md
template.yaml

@abhgupta @damemi 
Updates to the README and template, brought the template here in line with what is in our ansible role.
To deploy, you can use `oc create/oc process/oc apply` outlined in the README.

README updates

---

cmd/hibernate/cmd.go
pkg/idling/autoidle.go
template.yaml

@dgoodwin  I missed this with the recent prometheus  namespace change, please merge, thanks!

fix prometheus url

---

OWNERS

@tiwillia this file is necessary for the ci-bot.  Please merge

add OWNERS file for ci

---

pkg/cache/cache.go
pkg/cache/resource-store.go
pkg/cache/resource-store_test.go
pkg/forcesleep/forcesleep.go
pkg/forcesleep/forcesleep_test.go
pkg/idling/autoidle.go
pkg/idling/autoidle_test.go
pkg/idling/idle.go

Add replicasets and deployments

---

README.md
template.yaml

@damemi please review, I missed the template update with the PR that adds replicasets/deployments.  
Thanks!

update template and README

---

template.yaml

@damemi can you give this a :+1:

sync template with oso_hibernation role

---

README.md
template.yaml

Merge master into stg

---

ansible/hibernation.yml
ansible/roles/oso_hibernation/README.md
ansible/roles/oso_hibernation/defaults/main.yml
ansible/roles/oso_hibernation/meta/main.yml
ansible/roles/oso_hibernation/tasks/main.yml
ansible/roles/oso_hibernation/tasks/uninstall.yml
ansible/roles/oso_hibernation/templates/hibernation-template.yaml.j2

@damemi @dak1n1 please review, thanks
this depends on https://github.com/openshift/online/pull/1643

move ansible role from online to online-hibernation

---

ansible/roles/oso_hibernation/tasks/main.yml
ansible/roles/oso_hibernation/templates/hibernation-template.yaml.j2

@damemi @dak1n1 
This will allow us to collect prometheus metrics from the hibernation component.

add annotations to service to collect prometheus metrics

---

ansible/roles/oso_hibernation/templates/hibernation-template.yaml.j2

Edit idle sync period to 8 hrs

---

pkg/idling/autoidle.go
pkg/idling/autoidle_test.go

@abhgupta @dak1n1 
woohoo - fixed the panic

fix index out of range panic when len(pod.RunningTimes) == 0

---

ansible/roles/oso_hibernation/defaults/main.yml
ansible/roles/oso_hibernation/tasks/main.yml

@abhgupta Testing in devenv without the rpm, have to add this directory check for 'tier=starter'

Ansible-ensure template directory exists

---

pkg/idling/autoidle.go
pkg/idling/autoidle_test.go

@damemi this is the fix for 
https://github.com/openshift/online-hibernation/issues/55

fix panic when auto-idler can't access prometheus

---

ansible/roles/oso_hibernation/defaults/main.yml
ansible/roles/oso_hibernation/templates/hibernation-template.yaml.j2
cmd/hibernate/cmd.go
pkg/cache/cache.go
pkg/cache/resource-store.go
pkg/cache/resource-store_test.go
pkg/forcesleep/forcesleep_test.go
pkg/idling/autoidle.go
pkg/idling/autoidle_test.go

#57 
https://github.com/openshift/online/pull/1750

Use namespace label to include projects for online-hibernation
